{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-serialization",
    "version": "2.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-sources.jar",
          "url": "kotlin-serialization-2.1.10-sources.jar",
          "size": 2629,
          "sha512": "622c1db2ea8845fd74a66268214d8b23f7bd803c03a180a8e6ba2df2a4f546cc05c86b48c39c5dc23161dfd3a25f086c7e1a9c1fad1cbd5663affc29fa46a90c",
          "sha256": "1a99a42a89b5401ba7647d0f3ea4196ca14ab7a9b418e084e7d025db1a744090",
          "sha1": "6317999321440bc23e2baacae95c4cc927f90b8a",
          "md5": "36eb3d8f8c947abad6dd40f3b3af3ff1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-javadoc.jar",
          "url": "kotlin-serialization-2.1.10-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10.jar",
          "url": "kotlin-serialization-2.1.10.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10.jar",
          "url": "kotlin-serialization-2.1.10.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ]
    },
    {
      "name": "gradle80JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle80-javadoc.jar",
          "url": "kotlin-serialization-2.1.10-gradle80-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle80-sources.jar",
          "url": "kotlin-serialization-2.1.10-gradle80-sources.jar",
          "size": 2629,
          "sha512": "622c1db2ea8845fd74a66268214d8b23f7bd803c03a180a8e6ba2df2a4f546cc05c86b48c39c5dc23161dfd3a25f086c7e1a9c1fad1cbd5663affc29fa46a90c",
          "sha256": "1a99a42a89b5401ba7647d0f3ea4196ca14ab7a9b418e084e7d025db1a744090",
          "sha1": "6317999321440bc23e2baacae95c4cc927f90b8a",
          "md5": "36eb3d8f8c947abad6dd40f3b3af3ff1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle80.jar",
          "url": "kotlin-serialization-2.1.10-gradle80.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle80.jar",
          "url": "kotlin-serialization-2.1.10-gradle80.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle81JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle81-javadoc.jar",
          "url": "kotlin-serialization-2.1.10-gradle81-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle81-sources.jar",
          "url": "kotlin-serialization-2.1.10-gradle81-sources.jar",
          "size": 2629,
          "sha512": "622c1db2ea8845fd74a66268214d8b23f7bd803c03a180a8e6ba2df2a4f546cc05c86b48c39c5dc23161dfd3a25f086c7e1a9c1fad1cbd5663affc29fa46a90c",
          "sha256": "1a99a42a89b5401ba7647d0f3ea4196ca14ab7a9b418e084e7d025db1a744090",
          "sha1": "6317999321440bc23e2baacae95c4cc927f90b8a",
          "md5": "36eb3d8f8c947abad6dd40f3b3af3ff1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle81.jar",
          "url": "kotlin-serialization-2.1.10-gradle81.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle81.jar",
          "url": "kotlin-serialization-2.1.10-gradle81.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle82JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle82-javadoc.jar",
          "url": "kotlin-serialization-2.1.10-gradle82-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle82-sources.jar",
          "url": "kotlin-serialization-2.1.10-gradle82-sources.jar",
          "size": 2629,
          "sha512": "622c1db2ea8845fd74a66268214d8b23f7bd803c03a180a8e6ba2df2a4f546cc05c86b48c39c5dc23161dfd3a25f086c7e1a9c1fad1cbd5663affc29fa46a90c",
          "sha256": "1a99a42a89b5401ba7647d0f3ea4196ca14ab7a9b418e084e7d025db1a744090",
          "sha1": "6317999321440bc23e2baacae95c4cc927f90b8a",
          "md5": "36eb3d8f8c947abad6dd40f3b3af3ff1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle82.jar",
          "url": "kotlin-serialization-2.1.10-gradle82.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle82.jar",
          "url": "kotlin-serialization-2.1.10-gradle82.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle85JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle85-javadoc.jar",
          "url": "kotlin-serialization-2.1.10-gradle85-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle85-sources.jar",
          "url": "kotlin-serialization-2.1.10-gradle85-sources.jar",
          "size": 2629,
          "sha512": "622c1db2ea8845fd74a66268214d8b23f7bd803c03a180a8e6ba2df2a4f546cc05c86b48c39c5dc23161dfd3a25f086c7e1a9c1fad1cbd5663affc29fa46a90c",
          "sha256": "1a99a42a89b5401ba7647d0f3ea4196ca14ab7a9b418e084e7d025db1a744090",
          "sha1": "6317999321440bc23e2baacae95c4cc927f90b8a",
          "md5": "36eb3d8f8c947abad6dd40f3b3af3ff1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle85.jar",
          "url": "kotlin-serialization-2.1.10-gradle85.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.1.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-serialization-2.1.10-gradle85.jar",
          "url": "kotlin-serialization-2.1.10-gradle85.jar",
          "size": 6062,
          "sha512": "4e2d4b1b7cc281ea33409e63a4dd20ca746879a5620e8051dbe97e316882d49d90abed634a7cb9642148b5eb5072ff71ed36172aef4876a2a42ac0b134d09e0d",
          "sha256": "31608d7661c6c3fa3dd647d7511f1a8e5a0bacaf1674cd7a1893966503f4956b",
          "sha1": "057fafb0877218fbcdc977bc0e73c8485237c875",
          "md5": "71c8544d068ff53e6a6cb8d303af996b"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-serialization",
          "version": "2.1.10"
        }
      ]
    }
  ]
}
