{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-client-core",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websocket-serialization",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-sse",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-core-metadata-3.0.3.jar",
          "url": "ktor-client-core-3.0.3.jar",
          "size": 83133,
          "sha512": "49f22a2eea25aa3077f030b5e91040a551da42fad73f415bfd64dc8d94d73d5137c0c2098d9d64e31b4ef039b861869a0725fbfed856c1c6999759b5a30b1b7e",
          "sha256": "d5e586cb5a92608c7c12ee61f50d90358b59b524d6ba25ce13d2ee26a5fceff8",
          "sha1": "b4426c85defd14bc629c73aa3c9cb65645182261",
          "md5": "a5f642c3d0296c2a495142115bc7ab57"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-client-core-kotlin-3.0.3-sources.jar",
          "url": "ktor-client-core-3.0.3-sources.jar",
          "size": 128310,
          "sha512": "71cf194056b96b626179c9ea00db1d5ad62cd9380a9e04c47befb914b89649e35b061812b966287bfbdfea24ffaabdce4efba4b8f8c9f37cf50f0e2c01412be9",
          "sha256": "49e3499059be7ae4c0fe68e65e4d41c7344dbb8131bf7b0726040f1ec4362544",
          "sha1": "12879595e1b2917a43e4a9b2325c7d20fc41b32d",
          "md5": "76bfb49eb452b0e93f899e7fada8b54d"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativearm32/3.0.3/ktor-client-core-androidnativearm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativearm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativearm32/3.0.3/ktor-client-core-androidnativearm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativearm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativearm64/3.0.3/ktor-client-core-androidnativearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativearm64/3.0.3/ktor-client-core-androidnativearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativex64/3.0.3/ktor-client-core-androidnativex64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativex64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativex64/3.0.3/ktor-client-core-androidnativex64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativex64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativex86/3.0.3/ktor-client-core-androidnativex86-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativex86",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-androidnativex86/3.0.3/ktor-client-core-androidnativex86-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-androidnativex86",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosarm64/3.0.3/ktor-client-core-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosarm64/3.0.3/ktor-client-core-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosarm64/3.0.3/ktor-client-core-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iossimulatorarm64/3.0.3/ktor-client-core-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iossimulatorarm64/3.0.3/ktor-client-core-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iossimulatorarm64/3.0.3/ktor-client-core-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosx64/3.0.3/ktor-client-core-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosx64/3.0.3/ktor-client-core-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosx64/3.0.3/ktor-client-core-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-js/3.0.3/ktor-client-core-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-js/3.0.3/ktor-client-core-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-js/3.0.3/ktor-client-core-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-core-jvm/3.0.3/ktor-client-core-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-core-jvm/3.0.3/ktor-client-core-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-core-jvm/3.0.3/ktor-client-core-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxarm64/3.0.3/ktor-client-core-linuxarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxarm64/3.0.3/ktor-client-core-linuxarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxx64/3.0.3/ktor-client-core-linuxx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxx64/3.0.3/ktor-client-core-linuxx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosarm64/3.0.3/ktor-client-core-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosarm64/3.0.3/ktor-client-core-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosarm64/3.0.3/ktor-client-core-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosx64/3.0.3/ktor-client-core-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosx64/3.0.3/ktor-client-core-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosx64/3.0.3/ktor-client-core-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-mingwx64/3.0.3/ktor-client-core-mingwx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-mingwx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-mingwx64/3.0.3/ktor-client-core-mingwx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-mingwx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosarm64/3.0.3/ktor-client-core-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosarm64/3.0.3/ktor-client-core-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosarm64/3.0.3/ktor-client-core-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvossimulatorarm64/3.0.3/ktor-client-core-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvossimulatorarm64/3.0.3/ktor-client-core-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvossimulatorarm64/3.0.3/ktor-client-core-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosx64/3.0.3/ktor-client-core-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosx64/3.0.3/ktor-client-core-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosx64/3.0.3/ktor-client-core-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-wasm-js/3.0.3/ktor-client-core-wasm-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-wasm-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-wasm-js/3.0.3/ktor-client-core-wasm-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-wasm-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-wasm-js/3.0.3/ktor-client-core-wasm-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-wasm-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm32/3.0.3/ktor-client-core-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm32/3.0.3/ktor-client-core-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm32/3.0.3/ktor-client-core-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm64/3.0.3/ktor-client-core-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm64/3.0.3/ktor-client-core-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm64/3.0.3/ktor-client-core-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosdevicearm64/3.0.3/ktor-client-core-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosdevicearm64/3.0.3/ktor-client-core-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosdevicearm64/3.0.3/ktor-client-core-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchossimulatorarm64/3.0.3/ktor-client-core-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchossimulatorarm64/3.0.3/ktor-client-core-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchossimulatorarm64/3.0.3/ktor-client-core-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosx64/3.0.3/ktor-client-core-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosx64/3.0.3/ktor-client-core-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosx64/3.0.3/ktor-client-core-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosx64",
        "version": "3.0.3"
      }
    }
  ]
}
