{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-serialization-kotlinx-json",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-metadata-3.0.3.jar",
          "url": "ktor-serialization-kotlinx-json-3.0.3.jar",
          "size": 7298,
          "sha512": "0ec0c6738883828525eb011d186ef00a2ff9b0d9ef2c1773460324f3e5895231ec83927165492122ad5cf10c3aaa8a3edc7041b9b4df96dcb15b47530344d23b",
          "sha256": "b6d394d543f2ed5a80040d56bd9cc7b9e9847e54d10f537360d7172e8bf867a0",
          "sha1": "756e4c385d1c6c2b74f9516fc7982cc57efeab79",
          "md5": "0292876a9da35e85536c80e0529458da"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-kotlin-3.0.3-sources.jar",
          "url": "ktor-serialization-kotlinx-json-3.0.3-sources.jar",
          "size": 6069,
          "sha512": "36204e060d98f3d5bb8ac2696f8c1d06fd9061c3e9bc4721aba0a15b9ff2ee6b31e276fc6298d929321bc7de473e1ab03e74d97178172ef07515a378e045b97d",
          "sha256": "c4b70f6c72bd009e455f04bc419356ea578efabba00356ec6893adbe919a2865",
          "sha1": "7560cd0c8a3e3c541aef743b51e09345c16b9563",
          "md5": "e931df6037b3d6f29704a9f3bb70388a"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativearm32/3.0.3/ktor-serialization-kotlinx-json-androidnativearm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativearm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativearm32/3.0.3/ktor-serialization-kotlinx-json-androidnativearm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativearm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativearm64/3.0.3/ktor-serialization-kotlinx-json-androidnativearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativearm64/3.0.3/ktor-serialization-kotlinx-json-androidnativearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativex64/3.0.3/ktor-serialization-kotlinx-json-androidnativex64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativex64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativex64/3.0.3/ktor-serialization-kotlinx-json-androidnativex64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativex64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativex86/3.0.3/ktor-serialization-kotlinx-json-androidnativex86-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativex86",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-androidnativex86/3.0.3/ktor-serialization-kotlinx-json-androidnativex86-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-androidnativex86",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iosarm64/3.0.3/ktor-serialization-kotlinx-json-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iosarm64/3.0.3/ktor-serialization-kotlinx-json-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iosarm64/3.0.3/ktor-serialization-kotlinx-json-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iosx64/3.0.3/ktor-serialization-kotlinx-json-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iosx64/3.0.3/ktor-serialization-kotlinx-json-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-iosx64/3.0.3/ktor-serialization-kotlinx-json-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-js/3.0.3/ktor-serialization-kotlinx-json-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-js/3.0.3/ktor-serialization-kotlinx-json-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-js/3.0.3/ktor-serialization-kotlinx-json-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-jvm/3.0.3/ktor-serialization-kotlinx-json-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-jvm/3.0.3/ktor-serialization-kotlinx-json-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-jvm/3.0.3/ktor-serialization-kotlinx-json-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-linuxarm64/3.0.3/ktor-serialization-kotlinx-json-linuxarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-linuxarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-linuxarm64/3.0.3/ktor-serialization-kotlinx-json-linuxarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-linuxarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-linuxx64/3.0.3/ktor-serialization-kotlinx-json-linuxx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-linuxx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-linuxx64/3.0.3/ktor-serialization-kotlinx-json-linuxx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-linuxx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-macosarm64/3.0.3/ktor-serialization-kotlinx-json-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-macosarm64/3.0.3/ktor-serialization-kotlinx-json-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-macosarm64/3.0.3/ktor-serialization-kotlinx-json-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-macosx64/3.0.3/ktor-serialization-kotlinx-json-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-macosx64/3.0.3/ktor-serialization-kotlinx-json-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-macosx64/3.0.3/ktor-serialization-kotlinx-json-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-mingwx64/3.0.3/ktor-serialization-kotlinx-json-mingwx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-mingwx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-mingwx64/3.0.3/ktor-serialization-kotlinx-json-mingwx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-mingwx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvosarm64/3.0.3/ktor-serialization-kotlinx-json-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvosarm64/3.0.3/ktor-serialization-kotlinx-json-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvosarm64/3.0.3/ktor-serialization-kotlinx-json-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvosx64/3.0.3/ktor-serialization-kotlinx-json-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvosx64/3.0.3/ktor-serialization-kotlinx-json-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-tvosx64/3.0.3/ktor-serialization-kotlinx-json-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-wasm-js/3.0.3/ktor-serialization-kotlinx-json-wasm-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-wasm-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-wasm-js/3.0.3/ktor-serialization-kotlinx-json-wasm-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-wasm-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-wasm-js/3.0.3/ktor-serialization-kotlinx-json-wasm-js-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-wasm-js",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosarm32/3.0.3/ktor-serialization-kotlinx-json-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosarm32/3.0.3/ktor-serialization-kotlinx-json-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosarm32/3.0.3/ktor-serialization-kotlinx-json-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosarm64/3.0.3/ktor-serialization-kotlinx-json-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosarm64/3.0.3/ktor-serialization-kotlinx-json-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosarm64/3.0.3/ktor-serialization-kotlinx-json-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosdevicearm64/3.0.3/ktor-serialization-kotlinx-json-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosdevicearm64/3.0.3/ktor-serialization-kotlinx-json-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosdevicearm64/3.0.3/ktor-serialization-kotlinx-json-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchossimulatorarm64/3.0.3/ktor-serialization-kotlinx-json-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosx64/3.0.3/ktor-serialization-kotlinx-json-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosx64/3.0.3/ktor-serialization-kotlinx-json-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-kotlinx-json-watchosx64/3.0.3/ktor-serialization-kotlinx-json-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-serialization-kotlinx-json-watchosx64",
        "version": "3.0.3"
      }
    }
  ]
}
