{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-client-cio",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-metadata-3.0.3.jar",
          "url": "ktor-client-cio-3.0.3.jar",
          "size": 13376,
          "sha512": "c687042f922fab47525ec45dc154d29ab418d5240242c600a3b35b1c1321a77556683901aea4732b94d970061942a0e3caf2ad98c6c8db47ac8f9af91bed735a",
          "sha256": "25a5629ad4f7d633806a6490fcc6530e96d0c49b722e33829f5536eb498fb2b9",
          "sha1": "59f40465568f6661bd4f772bc2611998098f061e",
          "md5": "c759af2a2d4de2d0b11fc7621543a723"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-client-cio-kotlin-3.0.3-sources.jar",
          "url": "ktor-client-cio-3.0.3-sources.jar",
          "size": 15572,
          "sha512": "740da5cba47321c02157b42fbcfdf7cf3c9beb10ab1bdb1e44d53d66bb7f14d17484cf6290793eb307fcba973f42812e84550fddb0fe292fffc977113c77ca5f",
          "sha256": "b02c990cfe8a593158f8166c5dc4476563d731ed18f3c1c39cd31e3a4e29a6d3",
          "sha1": "86c67b971f052d5ba04f0bfd35e6e6db4282bcf7",
          "md5": "6cae9763f0d96b9022e098cf847b127e"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativearm32/3.0.3/ktor-client-cio-androidnativearm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativearm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativearm32/3.0.3/ktor-client-cio-androidnativearm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativearm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativearm64/3.0.3/ktor-client-cio-androidnativearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativearm64/3.0.3/ktor-client-cio-androidnativearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativex64/3.0.3/ktor-client-cio-androidnativex64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativex64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativex64/3.0.3/ktor-client-cio-androidnativex64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativex64",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativex86/3.0.3/ktor-client-cio-androidnativex86-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativex86",
        "version": "3.0.3"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-androidnativex86/3.0.3/ktor-client-cio-androidnativex86-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-androidnativex86",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosarm64/3.0.3/ktor-client-cio-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosarm64/3.0.3/ktor-client-cio-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosarm64/3.0.3/ktor-client-cio-iosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iossimulatorarm64/3.0.3/ktor-client-cio-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iossimulatorarm64/3.0.3/ktor-client-cio-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iossimulatorarm64/3.0.3/ktor-client-cio-iossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosx64/3.0.3/ktor-client-cio-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosx64/3.0.3/ktor-client-cio-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosx64/3.0.3/ktor-client-cio-iosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-cio-jvm/3.0.3/ktor-client-cio-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-cio-jvm/3.0.3/ktor-client-cio-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-cio-jvm/3.0.3/ktor-client-cio-jvm-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-jvm",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxarm64/3.0.3/ktor-client-cio-linuxarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxarm64/3.0.3/ktor-client-cio-linuxarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxx64/3.0.3/ktor-client-cio-linuxx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxx64/3.0.3/ktor-client-cio-linuxx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosarm64/3.0.3/ktor-client-cio-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosarm64/3.0.3/ktor-client-cio-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosarm64/3.0.3/ktor-client-cio-macosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosx64/3.0.3/ktor-client-cio-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosx64/3.0.3/ktor-client-cio-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosx64/3.0.3/ktor-client-cio-macosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-mingwx64/3.0.3/ktor-client-cio-mingwx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-mingwx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-mingwx64/3.0.3/ktor-client-cio-mingwx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-mingwx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosarm64/3.0.3/ktor-client-cio-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosarm64/3.0.3/ktor-client-cio-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosarm64/3.0.3/ktor-client-cio-tvosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvossimulatorarm64/3.0.3/ktor-client-cio-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvossimulatorarm64/3.0.3/ktor-client-cio-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvossimulatorarm64/3.0.3/ktor-client-cio-tvossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosx64/3.0.3/ktor-client-cio-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosx64/3.0.3/ktor-client-cio-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosx64/3.0.3/ktor-client-cio-tvosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm32/3.0.3/ktor-client-cio-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm32/3.0.3/ktor-client-cio-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm32/3.0.3/ktor-client-cio-watchosarm32-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm32",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm64/3.0.3/ktor-client-cio-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm64/3.0.3/ktor-client-cio-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm64/3.0.3/ktor-client-cio-watchosarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosdevicearm64/3.0.3/ktor-client-cio-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosdevicearm64/3.0.3/ktor-client-cio-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosdevicearm64/3.0.3/ktor-client-cio-watchosdevicearm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosdevicearm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchossimulatorarm64/3.0.3/ktor-client-cio-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchossimulatorarm64/3.0.3/ktor-client-cio-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchossimulatorarm64/3.0.3/ktor-client-cio-watchossimulatorarm64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchossimulatorarm64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosx64/3.0.3/ktor-client-cio-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosx64/3.0.3/ktor-client-cio-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosx64",
        "version": "3.0.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosx64/3.0.3/ktor-client-cio-watchosx64-3.0.3.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosx64",
        "version": "3.0.3"
      }
    }
  ]
}
